/**
 * 2026/12 沖繩 5天4夜自駕行程資料庫
 * 行程名稱：2026/12沖繩
 * 行程來源：去趣 ChicTrip (https://chictrip-share.app.link/SOyJSS7fi6b)
 */

const TRIP_METADATA = {
  id: "okinawa-2026-12",
  title: "2026/12 沖繩冬日海風自由行",
  subTitle: "OKINAWA 5-DAY ROAD TRIP & GOURMET TOUR",
  originalTitle: "2026/12沖繩",
  dateRange: "2026/12/12 (六) - 2026/12/16 (三)",
  daysCount: 5,
  nightsCount: 4,
  departureDate: "2026-12-12T11:00:00+09:00",
  chictripUrl: "https://chictrip-share.app.link/SOyJSS7fi6b",
  baseLocation: {
    name: "Ocean Tree (海之樹)",
    description: "旅程核心下榻別墅/公寓，位於沖繩南部，臨海環境優美，做為每日出發與歸營的安心港灣。",
    lat: 26.1360,
    lng: 127.6780
  },
  stats: {
    totalScheduleEvents: 40,
    uniqueSpots: 31,
    totalShopping: 12,
    totalFood: 8,
    totalAttraction: 7,
    totalTransitHotel: 13
  },
  themeHighlights: [
    { title: "美式好市多 × 週六美國村煙火", icon: "🎆", desc: "初訪南城全新好市多大採購，夜晚直奔北谷美國村欣賞週六限定璀璨海濱煙火秀。" },
    { title: "南部海味 × 水族沉浸 × 漁民食堂", icon: "🐟", desc: "糸滿魚市場現剖生魚片大餐、新世代DMM光影水族館、排隊名店奶油香煎魚。" },
    { title: "市區免稅 × 雙神社參拜 × 瀨長島夕陽", icon: "⛩️", desc: "波上宮海崖絕景、奧武山護國神社求平安、DFS免稅名品、排隊文青沖繩麵EIBUN與小希臘夕陽。" },
    { title: "PARCO CITY海景巨型商場 × 雙炸豬排", icon: "🛍️", desc: "達磨寺祈求開運不倒翁、敘敘苑海景燒肉、PARCO CITY停留5小時痛快血拼、小やじ與かつ乃屋雙豬排饗宴。" },
    { title: "道之驛小農 × AEON採買 × 通堂拉麵", icon: "🍜", desc: "豐崎道之驛伴手禮、小祿AEON最後補貨、通堂經典男人麵/女人麵為旅途劃下完美句點。" }
  ]
};

const DAY_SUMMARIES = [
  {
    day: 1,
    date: "2026/12/12",
    dayOfWeek: "星期六",
    title: "首日啟程・好市多採購・北谷美國村週末煙火",
    tagline: "自駕首航！南部好市多狂歡與週六限定美村海濱夜空花火",
    themeColor: "#0284c7",
    stopsCount: 7
  },
  {
    day: 2,
    date: "2026/12/13",
    dayOfWeek: "星期日",
    title: "糸滿魚市場海鮮・iias水族館・漁民食堂名店",
    tagline: "海味爆棚的一天！現剖生魚片海膽、海景巨城與光影水族館",
    themeColor: "#0891b2",
    stopsCount: 7
  },
  {
    day: 3,
    date: "2026/12/14",
    dayOfWeek: "星期一",
    title: "雙神社參拜・DFS免稅・文青EIBUN麵・瀨長島夕陽",
    tagline: "那霸文化與時尚的一日英哩，崖上海景波上宮與小希臘落日",
    themeColor: "#2563eb",
    stopsCount: 11
  },
  {
    day: 4,
    date: "2026/12/15",
    dayOfWeek: "星期二",
    title: "達磨寺祈福・敘敘苑海景燒肉・PARCO CITY狂逛5小時・雙豬排巡禮",
    tagline: "極致購物與肉食狂歡！沖繩最大海景商城與日式酥脆豬排雙饗宴",
    themeColor: "#7c3aed",
    stopsCount: 9
  },
  {
    day: 5,
    date: "2026/12/16",
    dayOfWeek: "星期三",
    title: "豐崎道之驛小農・AEON最後補貨・通堂拉麵經典・還車返台",
    tagline: "滿載而歸！特產採購衝刺、傳奇通堂拉麵與機場溫馨道別",
    themeColor: "#d97706",
    stopsCount: 6
  }
];

const SCHEDULE_ITEMS = [
  // DAY 1 (2026/12/12)
  {
    id: "d1-1",
    day: 1,
    date: "2026/12/12",
    time: "11:00",
    name: "Toyota Rental Car Naha Airport Branch",
    nameZh: "Toyota租車 沖繩那霸機場店",
    nameJa: "トヨタレンタカー 那覇空港店",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "transport",
    categoryLabel: "交通取車",
    icon: "🚗",
    lat: 26.1915,
    lng: 127.6590,
    address: "沖縄県那覇市赤嶺2丁目13-1",
    mapCode: "33 064 577*55",
    googleQuery: "Toyota Rental Car Naha Airport Branch",
    tags: ["自駕首站", "機場接駁", "右駕手續"],
    desc: "抵達那霸機場後搭乘豐田專屬免費接駁巴士直達營業所。辦理取車手續、出示台灣駕照正本與日文譯本、確認加保安心免責險(NOC)、詳細檢查車體外觀並熟悉右駕按鍵與車載GPS導航。",
    tips: "取車時務必繞車一圈錄影或拍照記錄微小刮痕；熟悉右側方向燈撥桿與雨刷位置；設定好首站導航。"
  },
  {
    id: "d1-2",
    day: 1,
    date: "2026/12/12",
    time: "12:15",
    name: "San-A 塩崎",
    nameZh: "SAN-A 潮崎購物城 (San-A Shiozaki)",
    nameJa: "サンエー しおざきシティ",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "shopping",
    categoryLabel: "補給採買",
    icon: "🛒",
    lat: 26.1305,
    lng: 127.6710,
    address: "沖縄県糸満市潮崎町2丁目2",
    mapCode: "232 425 447*88",
    googleQuery: "サンエー しおざきシティ",
    tags: ["南部大型超市", "隨車補給", "日用品食品"],
    desc: "沖繩南部在地人最信賴的連鎖大型綜合商場。初抵沖繩立即採購隨車礦泉水、Sanpin香片茶、防曬噴霧、零食、水果及旅程初期隨身生活物資，好逛且價格親民。",
    tips: "設有超大型平面免費停車場；商場內附設美食街與烘焙坊，亦可簡單點心充飢。"
  },
  {
    id: "d1-3",
    day: 1,
    date: "2026/12/12",
    time: "13:20",
    name: "Ocean Tree",
    nameZh: "Ocean Tree (海之樹 旅宿Check-in)",
    nameJa: "オーシャンツリー",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "hotel",
    categoryLabel: "旅宿休整",
    icon: "🏡",
    lat: 26.1360,
    lng: 127.6780,
    address: "沖縄県糸満/南部海岸エリア",
    mapCode: "232 456 123*45",
    googleQuery: "Ocean Tree Okinawa",
    tags: ["行程基地", "海景旅宿", "寄存行李"],
    desc: "抵達本次沖繩旅程的核心基地 Ocean Tree！辦理入住登記、寄存大件行李、換穿輕便衣物，推開窗感受南國溫柔海風，稍作休整。",
    tips: "確認房門密碼鎖及停車位位置；檢查隨身好市多會員卡準備下午採購。"
  },
  {
    id: "d1-4",
    day: 1,
    date: "2026/12/12",
    time: "14:50",
    name: "COSTCO好市多 沖繩店",
    nameZh: "COSTCO 好市多 沖繩南城倉庫店",
    nameJa: "コストコホールセール 沖縄南城倉庫店",
    duration: "停留 02時30分",
    durationMinutes: 150,
    category: "shopping",
    categoryLabel: "巨型量販",
    icon: "🛍️",
    lat: 26.1558,
    lng: 127.7712,
    address: "沖縄県南城市つきしろ1071-1",
    mapCode: "232 509 780*14",
    googleQuery: "Costco Wholesale Okinawa Nanjo",
    tags: ["沖繩首間好市多", "限定美食", "派對熟食"],
    desc: "2024年秋季轟動登場的沖繩第一間好市多！佔地遼闊，除各類美式超值商品外，更有沖繩黑糖點心、石垣牛肉排、在地特產，是自駕族群採買派對派對美食與宵夜的大天堂！",
    tips: "台灣好市多實體會員卡全球通用；熟食部的沖繩限定風味披薩、大熱狗與蛤蜊濃湯不可錯過。"
  },
  {
    id: "d1-5",
    day: 1,
    date: "2026/12/12",
    time: "17:49",
    name: "Ocean Tree",
    nameZh: "Ocean Tree (放戰利品・換裝準備出發)",
    nameJa: "オーシャンツリー",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "hotel",
    categoryLabel: "中途休整",
    icon: "🏡",
    lat: 26.1360,
    lng: 127.6780,
    address: "沖縄県糸満/南部海岸エリア",
    mapCode: "232 456 123*45",
    googleQuery: "Ocean Tree Okinawa",
    tags: ["戰利品卸貨", "補水修整", "出發北谷"],
    desc: "返回Ocean Tree將好市多採購的冷藏食物與戰利品歸位，稍微盥洗補妝，攜帶防風外套準備北上北谷町觀賞週六專屬的美濱煙火秀。",
    tips: "沖繩傍晚5點至7點主幹道（58號公路）偶有下班車潮，保留充足行車時間。"
  },
  {
    id: "d1-6",
    day: 1,
    date: "2026/12/12",
    time: "19:38",
    name: "美國村煙火觀賞點",
    nameZh: "北谷美國村 週末煙火觀賞點",
    nameJa: "美浜アメリカンビレッジ 花火ビューポイント",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "attraction",
    categoryLabel: "限定景觀",
    icon: "🎆",
    lat: 26.3165,
    lng: 127.7565,
    address: "沖縄県中頭郡北谷町美浜 (日落海灘/海濱步道)",
    mapCode: "33 526 452*52",
    googleQuery: "American Village Fireworks Chatan Okinawa",
    tags: ["週六限定煙火", "美式夜景", "浪漫海濱"],
    desc: "北谷美國村每逢週六晚間（約20:00）定期施放燦爛海濱煙火！在充滿美式復古霓虹街景、棕櫚樹與海潮聲中，抬頭欣賞夜空綻放的璀璨光芒，浪漫無比！",
    tips: "日落海灘（Sunset Beach）堤防或Depot Island Boardwalk海邊棧道是最佳觀賞點；周邊有公共大型免費停車場。"
  },
  {
    id: "d1-7",
    day: 1,
    date: "2026/12/12",
    time: "21:25",
    name: "Ocean Tree",
    nameZh: "Ocean Tree (夜宿歸營)",
    nameJa: "オーシャンツリー",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "hotel",
    categoryLabel: "旅宿晚安",
    icon: "🌙",
    lat: 26.1360,
    lng: 127.6780,
    address: "沖縄県糸満/南部海岸エリア",
    mapCode: "232 456 123*45",
    googleQuery: "Ocean Tree Okinawa",
    tags: ["首日圓滿", "好市多宵夜", "養精蓄銳"],
    desc: "返回Ocean Tree結束精彩的第一天自駕行程。開一罐沖繩Orion啤酒，搭配好市多美食與零嘴，與旅伴暢聊，好好休息為第二天的海鮮魚市場儲備體力。",
    tips: "設定明晨07:30鬧鐘，準備空腹迎接第二天的現剖海鮮早餐！"
  },

  // DAY 2 (2026/12/13)
  {
    id: "d2-1",
    day: 2,
    date: "2026/12/13",
    time: "08:00",
    name: "Ocean Tree",
    nameZh: "Ocean Tree (晨起準備)",
    nameJa: "オーシャンツリー",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "hotel",
    categoryLabel: "晨間出發",
    icon: "🌅",
    lat: 26.1360,
    lng: 127.6780,
    address: "沖縄県糸満/南部海岸エリア",
    mapCode: "232 456 123*45",
    googleQuery: "Ocean Tree Okinawa",
    tags: ["早安南國", "空腹出發", "海味之旅"],
    desc: "在南國清澈晨光中醒來，品嚐早晨咖啡，欣賞蔚藍海平線，整理相機與隨身裝備，準備迎接南部著名的海鮮早餐！",
    tips: "空腹出發！留著胃口給魚市場的豪華生魚片與海膽。"
  },
  {
    id: "d2-2",
    day: 2,
    date: "2026/12/13",
    time: "09:06",
    name: "糸滿魚市場",
    nameZh: "糸滿魚市場 (道之驛糸滿魚市中心)",
    nameJa: "糸満漁業協同組合 お魚センター",
    duration: "停留 02時00分",
    durationMinutes: 120,
    category: "food",
    categoryLabel: "老饕海味",
    icon: "🍣",
    lat: 26.1438,
    lng: 127.6625,
    address: "沖縄県糸満市西崎町4丁目19",
    mapCode: "232 484 136*85",
    googleQuery: "糸満漁業協同組合 お魚センター",
    tags: ["現剖生魚片", "焗烤海膽龍蝦", "銅板海鮮", "大生蠔"],
    desc: "沖繩南部無人不知的海鮮朝聖地！室內一字排開十數間鮮魚攤位，陳列著只要300-500日圓的厚切生魚片、特大生蠔、甜蝦、海膽杯、焗烤海膽龍蝦與酥炸鮪魚排，現點現吃超滿足！",
    tips: "戶外設有遮陽用餐區與洗手台；推薦自備濕紙巾；旁邊還有物產館可買沖繩在地當季水果。"
  },
  {
    id: "d2-3",
    day: 2,
    date: "2026/12/13",
    time: "11:11",
    name: "Ocean Tree",
    nameZh: "Ocean Tree (回宿休整)",
    nameJa: "オーシャンツリー",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "hotel",
    categoryLabel: "中場休息",
    icon: "🏡",
    lat: 26.1360,
    lng: 127.6780,
    address: "沖縄県糸満/南部海岸エリア",
    mapCode: "232 456 123*45",
    googleQuery: "Ocean Tree Okinawa",
    tags: ["小憩放鬆", "避開正午太陽", "換裝出發"],
    desc: "在魚市場大快朵頤後，車程僅需數分鐘返回Ocean Tree。稍微放鬆小憩、整理戰利品與防曬，避開正午前最強烈的紫外線。",
    tips: "補充足夠水分，準備前往豐見城最新的巨型購物城iias。"
  },
  {
    id: "d2-4",
    day: 2,
    date: "2026/12/13",
    time: "12:21",
    name: "iias 沖繩豐崎",
    nameZh: "iias 沖繩豐崎 (大型海濱休閒商城)",
    nameJa: "イーアス沖縄豊崎",
    duration: "停留 03時00分",
    durationMinutes: 180,
    category: "shopping",
    categoryLabel: "海濱商城",
    icon: "🏬",
    lat: 26.1583,
    lng: 127.6536,
    address: "沖縄県豊見城市字豊崎3-35",
    mapCode: "232 543 400*25",
    googleQuery: "イーアス沖縄豊崎 iias Okinawa Toyosaki",
    tags: ["Uniqlo大型店", "Loft雜貨", "海景露台", "免稅購物"],
    desc: "2020年全新開幕的沖繩南部最大型購物中心！集結Uniqlo、GU大型店、Loft雜貨、KOJIMA電器、超大藥妝店及各大人氣服飾；頂層更設有恐龍主題戶外海景BBQ園區，面海景致極佳。",
    tips: "館內多數免稅店舖可合併辦理退稅手續；逛累了可到2F海景露台座位喝咖啡看海。"
  },
  {
    id: "d2-5",
    day: 2,
    date: "2026/12/13",
    time: "15:28",
    name: "DMM Kariyushi水族館",
    nameZh: "DMM Kariyushi水族館 (光影沉浸水族)",
    nameJa: "DMMかりゆし水族館",
    duration: "停留 00時30分",
    durationMinutes: 30,
    category: "attraction",
    categoryLabel: "沉浸科技",
    icon: "🐠",
    lat: 26.1578,
    lng: 127.6542,
    address: "沖縄県豊見城市字豊崎3-35 (iias商場內2F)",
    mapCode: "232 543 400*25",
    googleQuery: "DMM Kariyushi Aquarium Okinawa",
    tags: ["光影水族", "玻璃步道", "近距離企鵝", "數位藝術"],
    desc: "緊鄰iias商場的新世代水族館，將尖端投影技術與海洋生態完美結合！步入腳下懸空透明玻璃的水槽步道、觀察自在悠游的魟魚與熱帶魚，還能近距離看到樹獺、大嘴鳥與企鵝！",
    tips: "場館精緻緊湊、動線流暢，30至45分鐘即可完整體驗精彩展區與光影互動秀。"
  },
  {
    id: "d2-6",
    day: 2,
    date: "2026/12/13",
    time: "16:05",
    name: "美麗SUN海灘",
    nameZh: "豐崎海濱公園 美麗SUN海灘",
    nameJa: "豊崎美らSUNビーチ",
    duration: "停留 00時30分",
    durationMinutes: 30,
    category: "attraction",
    categoryLabel: "絕美海灘",
    icon: "🏖️",
    lat: 26.1545,
    lng: 127.6508,
    address: "沖縄県豊見城市字豊崎5-1",
    mapCode: "232 542 328*33",
    googleQuery: "Toyosaki Seaside Park Chura-SUN Beach",
    tags: ["全長700米白沙", "看飛機起降", "日落散步", "南部第一灘"],
    desc: "沖繩南部全長超過700公尺的白砂人工海灘，就在iias商場正前方！可踏著細白沙灘漫步，近距離欣賞那霸機場起降航班掠過碧藍海空的震撼視角，微風徐徐非常治癒。",
    tips: "冬季海風較大，建議披上薄防風外套；傍晚落日時分天空會染上一層漸層粉紫金黃。"
  },
  {
    id: "d2-7",
    day: 2,
    date: "2026/12/13",
    time: "16:43",
    name: "糸滿漁民食堂",
    nameZh: "糸滿漁民食堂 (神級奶油香煎鮮魚)",
    nameJa: "糸満漁民食堂",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "food",
    categoryLabel: "名店晚餐",
    icon: "🐟",
    lat: 26.1472,
    lng: 127.6656,
    address: "沖縄県糸満市西崎町4丁目22-7",
    mapCode: "232 484 797*30",
    googleQuery: "糸満漁民食堂 Itoman Gyomin Shokudo",
    tags: ["鐵板奶油煎魚", "琉球石灰岩建築", "排隊神店", "鮮魚定食"],
    desc: "沖繩南部必吃第一名！由當地琉球石灰岩匠人堆砌的優雅外觀，鎮店之寶是鐵盤上滋滋作響的「奶油香煎時令魚（魚のバター焼き）」，可自選蒜味、海苔或辣味奶油，香濃無比，魚肉外酥內嫩汁水飽滿！",
    tips: "名店經常大排長龍，提早於晚餐開始前抵達登記候位最保險；定食隨附新鮮魚湯與三道小菜極度超值。"
  },

  // DAY 3 (2026/12/14)
  {
    id: "d3-1",
    day: 3,
    date: "2026/12/14",
    time: "08:00",
    name: "Ocean Tree",
    nameZh: "Ocean Tree (晨起準備)",
    nameJa: "オーシャンツリー",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "hotel",
    categoryLabel: "晨間出發",
    icon: "🌅",
    lat: 26.1360,
    lng: 127.6780,
    address: "沖縄県糸満/南部海岸エリア",
    mapCode: "232 456 123*45",
    googleQuery: "Ocean Tree Okinawa",
    tags: ["那霸精華日", "神社祈福", "市區免稅"],
    desc: "旅程第三天將全日造訪沖繩首府那霸市區！早晨悠閒享用早餐，準備走訪神社參拜、市區DFS免稅狂歡、國際通名物與瀨長島日落。",
    tips: "那霸市區白天車流較多，留意導航路況並備妥零錢停車。"
  },
  {
    id: "d3-2",
    day: 3,
    date: "2026/12/14",
    time: "09:22",
    name: "沖繩縣護國神社",
    nameZh: "沖繩縣護國神社",
    nameJa: "沖縄県護国神社",
    duration: "停留 00時30分",
    durationMinutes: 30,
    category: "attraction",
    categoryLabel: "神社參拜",
    icon: "⛩️",
    lat: 26.2039,
    lng: 127.6749,
    address: "沖縄県那覇市奥武山町44",
    mapCode: "33 126 127*41",
    googleQuery: "沖繩縣護國神社 Okinawa Gokoku Shrine",
    tags: ["奧武山公園", "莊嚴清幽", "求闔家平安"],
    desc: "坐落於奧武山公園林蔭綠意中，是沖繩參拜祈願名所。巨大紅色鳥居與開闊參道帶來平靜祥和氛圍，祈求心願成就與旅程平平安安。",
    tips: "公園內設有專屬免費停車場；神社境內古木參天，早晨散步空氣清新怡人。"
  },
  {
    id: "d3-3",
    day: 3,
    date: "2026/12/14",
    time: "10:04",
    name: "波上宮",
    nameZh: "波上宮 (沖繩總鎮守・懸崖海景神社)",
    nameJa: "波上宮 (なみのうえぐう)",
    duration: "停留 00時30分",
    durationMinutes: 30,
    category: "attraction",
    categoryLabel: "琉球八社之首",
    icon: "⛩️",
    lat: 26.2205,
    lng: 127.6713,
    address: "沖縄県那覇市若狭1丁目25-11",
    mapCode: "33 185 023*22",
    googleQuery: "波上宮 Naminoue Shrine Okinawa",
    tags: ["琉球八社第一", "珊瑚崖海景", "小學生書包御守", "波之上海灘"],
    desc: "佇立於珊瑚礁斷崖之上的琉球第一神社！朱紅色本殿襯著蔚藍晴空與浩瀚太平洋，氣勢非凡。最具代表性的紀念品是紅黑兩色的精緻小學生書包交通安全御守！",
    tips: "參拜後可步行至一旁的波之上沙灘橋上，回望拍下矗立在斷崖上的神社經典明信片角度。"
  },
  {
    id: "d3-4",
    day: 3,
    date: "2026/12/14",
    time: "10:51",
    name: "迪斐世 沖繩那霸店",
    nameZh: "T 廣場 by DFS 沖繩那霸店",
    nameJa: "Tギャラリア 沖縄 by DFS",
    duration: "停留 03時00分",
    durationMinutes: 180,
    category: "shopping",
    categoryLabel: "免稅精品",
    icon: "💎",
    lat: 26.2229,
    lng: 127.6976,
    address: "沖縄県那覇市おもろまち4-1",
    mapCode: "33 188 296*33",
    googleQuery: "T Galleria by DFS Okinawa",
    tags: ["日本唯一路面免稅", "一線精品全齊", "香氛化妝品", "歌町站"],
    desc: "全日本唯一的境內路面免稅店旗艦！匯聚Chanel、Louis Vuitton、Gucci、Cartier、Dior及全球各大頂級美妝保養品牌，免稅價極具吸引力，直接憑回程航班資訊於那霸機場管制區輕鬆提貨！",
    tips: "需出示回程航班機票資訊或預約確認信；館內提供大型室內免費停車場。"
  },
  {
    id: "d3-5",
    day: 3,
    date: "2026/12/14",
    time: "14:03",
    name: "那霸國際通商店街",
    nameZh: "那霸國際通商店街 (途經抵達)",
    nameJa: "那覇国際通り商店街",
    duration: "停留 00時00分",
    durationMinutes: 0,
    category: "shopping",
    categoryLabel: "繁華街區",
    icon: "🚶",
    lat: 26.2160,
    lng: 127.6875,
    address: "沖縄県那覇市牧志",
    mapCode: "33 157 382*41",
    googleQuery: "那覇国際通り商店街 Kokusai Dori",
    tags: ["奇蹟的一英哩", "街區核心", "步行美食"],
    desc: "全長1.6公里的沖繩最繁華主幹道「奇蹟的一英哩」。集合了傳統工藝、風獅爺手作、紫薯塔名店與特色居酒屋，此站作為進入牧志公設市場巷弄美食的起點。",
    tips: "國際通兩側皆為單行道或易塞車路段，建議將車輛停在周邊收費停車場（如平和通或壺屋周邊）步行進入。"
  },
  {
    id: "d3-6",
    day: 3,
    date: "2026/12/14",
    time: "14:10",
    name: "소키소바(Inaka Kosetsuichiba Minami-ten)",
    nameZh: "田舍 沖繩麵 (公設市場南店)",
    nameJa: "ソーキそば 田舎 公設市場南店",
    duration: "停留 00時00分",
    durationMinutes: 0,
    category: "food",
    categoryLabel: "庶民傳奇",
    icon: "🍜",
    lat: 26.2142,
    lng: 127.6882,
    address: "沖縄県那覇市松尾2丁目10-20",
    mapCode: "33 157 235*11",
    googleQuery: "ソーキそば 田舎 公設市場南店",
    tags: ["400円銅板美食", "軟骨入口即化", "巷弄隱藏版", "傳統老味"],
    desc: "隱身於第一牧志公設市場周邊窄巷的超平價傳奇沖繩麵！一碗招牌軟骨肉麵只要400-500日圓，深褐色的豬軟骨燉煮至晶瑩剔透、軟爛如布丁入口即化，濃郁柴魚豚骨高湯超銷魂！",
    tips: "店內座位精緻、只收現金；若客滿可作為雙麵比拼的對照組，立即步行4分鐘前往文青名店EIBUN。"
  },
  {
    id: "d3-7",
    day: 3,
    date: "2026/12/14",
    time: "14:14",
    name: "沖繩麵 EIBUN",
    nameZh: "沖繩麵 EIBUN (新世代文青話題名店)",
    nameJa: "OKINAWA SOBA EIBUN",
    duration: "停留 02時00分",
    durationMinutes: 120,
    category: "food",
    categoryLabel: "排隊冠軍",
    icon: "🍲",
    lat: 26.2117,
    lng: 127.6908,
    address: "沖縄県那覇市壺屋1丁目5-14",
    mapCode: "33 158 135*00",
    googleQuery: "OKINAWA SOBA EIBUN 那覇",
    tags: ["法式技藝跨界", "炙燒三層肉", "特選特製麵條", "沖繩第一話題"],
    desc: "顛覆傳統沖繩麵的當代排隊第一天王！由曾於法國料理修業的主廚打造，柴魚昆布慢火高湯清冽甘甜，招牌特選BUNSOBA盛滿了厚切炙燒三層肉、特選軟骨與嫩煎肉塊，更有多款風味辣油與柚子胡椒自由調配！",
    tips: "可使用門口平板登記排隊號碼，等候期間可順遊兩旁的壺屋陶瓷通漫步。"
  },
  {
    id: "d3-8",
    day: 3,
    date: "2026/12/14",
    time: "16:27",
    name: "Sports Depo Ameku",
    nameZh: "Sports Depo 天久店 (超大運動用品專賣)",
    nameJa: "スポーツデポ 天久店",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "shopping",
    categoryLabel: "戶外運動",
    icon: "👟",
    lat: 26.2307,
    lng: 127.6922,
    address: "沖縄県那覇市天久1-2-1 (天久樂市內)",
    mapCode: "33 218 074*74",
    googleQuery: "Sports Depo Ameku Naha",
    tags: ["露營登山", "球鞋服飾", "Coleman特賣", "免稅退稅"],
    desc: "那霸市區最大規模運動與戶外裝備量販店！齊聚The North Face、Nike、Adidas、Under Armour、Coleman露營裝備等，折扣幅度大且提供免稅服務，運動迷尋寶必逛！",
    tips: "同商場周邊還有Uniqlo與Best電器，附有超寬敞免費停車場。"
  },
  {
    id: "d3-9",
    day: 3,
    date: "2026/12/14",
    time: "17:54",
    name: "瀨長島",
    nameZh: "瀨長島 Umikaji Terrace (沖繩小希臘)",
    nameJa: "瀬長島ウミカジテラス",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "attraction",
    categoryLabel: "浪漫落日",
    icon: "🌅",
    lat: 26.1751,
    lng: 127.6415,
    address: "沖縄県豊見城市字瀬長174-6",
    mapCode: "33 002 602*06",
    googleQuery: "瀨長島 Umikaji Terrace",
    tags: ["小希臘純白建築", "飛機近距越頂", "海景夕陽", "幸福鬆餅"],
    desc: "依傍海島斜坡建起的一整排純白地中海風格階梯建築！傍晚時分金黃夕陽灑滿海面，客機以極近距離自頭頂掠過降落機場，震撼又夢幻。人氣名店「幸福鬆餅」亦座落於此！",
    tips: "落日時分是全日最美時刻；島上停車位熱門，建議順著道路指示停於防波堤公共免費停車區。"
  },
  {
    id: "d3-10",
    day: 3,
    date: "2026/12/14",
    time: "19:01",
    name: "美思佰樂 豐見城店",
    nameZh: "MaxValu 豐見城店 (24小時大型超市)",
    nameJa: "マックスバリュ 豊見城店",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "shopping",
    categoryLabel: "深夜超市",
    icon: "🛒",
    lat: 26.1668,
    lng: 127.6710,
    address: "沖縄県豊見城市字田頭155-1",
    mapCode: "33 034 656*33",
    googleQuery: "MaxValu Tomigusuku 豊見城",
    tags: ["24小時不打烊", "AEON旗下", "水果伴手禮", "熟食特價"],
    desc: "永旺AEON集團旗下24小時不打烊的生活超市！回民宿前的補給好幫手，採購新鮮當季草莓/蜜柑、日本鮮乳、泡盛、各款限定泡麵與宵夜熟食，晚間常有特價貼紙優惠！",
    tips: "買好隔天早晨的水果與飲料，免去清晨出門買早餐的匆忙。"
  },
  {
    id: "d3-11",
    day: 3,
    date: "2026/12/14",
    time: "20:14",
    name: "Ocean Tree",
    nameZh: "Ocean Tree (夜宿歸營)",
    nameJa: "オーシャンツリー",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "hotel",
    categoryLabel: "旅宿晚安",
    icon: "🌙",
    lat: 26.1360,
    lng: 127.6780,
    address: "沖縄県糸満/南部海岸エリア",
    mapCode: "232 456 123*45",
    googleQuery: "Ocean Tree Okinawa",
    tags: ["那霸戰利品", "微醺海風", "充飽電力"],
    desc: "帶著DFS免稅店提貨單與超市戰利品滿載而歸。在客廳享受沖繩微醺夜晚，迎接明天第四天的超狂PARCO CITY購物與敘敘苑頂級燒肉！",
    tips: "檢查隨身相機與行動電源充電狀態；整理這兩天累積的發票退稅單據。"
  },

  // DAY 4 (2026/12/15)
  {
    id: "d4-1",
    day: 4,
    date: "2026/12/15",
    time: "08:00",
    name: "Ocean Tree",
    nameZh: "Ocean Tree (晨起出發)",
    nameJa: "オーシャンツリー",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "hotel",
    categoryLabel: "晨間出發",
    icon: "🌅",
    lat: 26.1360,
    lng: 127.6780,
    address: "沖縄県糸満/南部海岸エリア",
    mapCode: "232 456 123*45",
    googleQuery: "Ocean Tree Okinawa",
    tags: ["祈福開運日", "頂級和牛燒肉", "巨型商城5小時"],
    desc: "早晨悠閒梳洗出發，今天將深入首里古道探訪開運達摩寺、享用敘敘苑海景午餐、在全沖繩最大的PARCO CITY購物中心停留5小時血拼，晚上更是日式炸豬排雙名店巡禮！",
    tips: "穿著最舒適好走的球鞋，準備應付5小時的馬拉松逛街！"
  },
  {
    id: "d4-2",
    day: 4,
    date: "2026/12/15",
    time: "09:34",
    name: "西來院 (達磨寺)",
    nameZh: "西來院 達磨寺 (滿滿開運不倒翁秘境)",
    nameJa: "西来院 達磨寺 (だるまでら)",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "attraction",
    categoryLabel: "私房開運",
    icon: "🎎",
    lat: 26.2185,
    lng: 127.7225,
    address: "沖縄県那覇市首里赤田町1丁目5",
    mapCode: "33 162 768*41",
    googleQuery: "西来院 達磨寺 首里",
    tags: ["開運達摩", "紅不倒翁牆", "求安產祈願", "首里秘境"],
    desc: "鄰近首里城的悠久禪宗名剎！寺內供奉達磨大師，階梯與殿前擺滿了信眾許願祈福的紅色不倒翁（達磨），十分壯觀吸睛！在此可求安產、求子、學業成就與開運必勝，氣氛寧靜肅穆。",
    tips: "可在境內求一顆專屬開運不倒翁，畫上左眼許下願望，待心願實現時再點上右眼。"
  },
  {
    id: "d4-3",
    day: 4,
    date: "2026/12/15",
    time: "10:36",
    name: "7-Eleven Shuri Castle Town JA Okinawa",
    nameZh: "7-Eleven 首里城下町JA沖繩店",
    nameJa: "セブン-イレブン 首里城下町JAおきなわ店",
    duration: "停留 00時20分",
    durationMinutes: 20,
    category: "shopping",
    categoryLabel: "便利小憩",
    icon: "🏪",
    lat: 26.2162,
    lng: 127.7185,
    address: "沖縄県那覇市首里当蔵町2丁目",
    mapCode: "33 161 685*00",
    googleQuery: "セブン-イレブン 首里城下町JAおきなわ店",
    tags: ["小七補給", "首里城門市", "特色冷飲"],
    desc: "融入首里琉球城下町古樸風貌的7-Eleven，自駕途中短暫休息，買杯招牌冰咖啡、特色茶飲或限定小點心，準備前往浦添西海岸。",
    tips: "利用門市洗手間與ATM，車程約20分鐘直達浦添西海岸PARCO CITY。"
  },
  {
    id: "d4-4",
    day: 4,
    date: "2026/12/15",
    time: "11:17",
    name: "敘敘苑 沖繩浦添PARCO CITY店",
    nameZh: "敘敘苑 燒肉 浦添PARCO CITY店",
    nameJa: "叙々苑 沖縄浦添パルコシティ店",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "food",
    categoryLabel: "頂級海景燒肉",
    icon: "🥩",
    lat: 26.2589,
    lng: 127.6972,
    address: "沖縄県浦添市西洲3-1-1 サンエー浦添西海岸 PARCO CITY 3F",
    mapCode: "33 339 024*42",
    googleQuery: "叙々苑 沖縄浦添パルコシティ店",
    tags: ["海景第一排", "東京燒肉之王", "午間超值套餐", "極品牛舌"],
    desc: "日本奢華燒肉代表「敘敘苑」進駐沖繩海景第一排！坐在面朝西海岸無邊蔚藍的落地窗席，細細品味油花勻稱的頂級特選牛五花、招牌敘敘苑特製沙拉、Q彈牛舌與精緻甜點，午間套餐CP值極高！",
    tips: "窗景座位極度熱門，建議提早於11:00前至店門口排隊或事前預約；飯後薄荷糖是經典招牌。"
  },
  {
    id: "d4-5",
    day: 4,
    date: "2026/12/15",
    time: "12:21",
    name: "SAN-A浦添西海岸 PARCO CITY",
    nameZh: "SAN-A 浦添西海岸 PARCO CITY",
    nameJa: "サンエー浦添西海岸 PARCO CITY",
    duration: "停留 05時00分",
    durationMinutes: 300,
    category: "shopping",
    categoryLabel: "沖繩最大購物旗艦",
    icon: "🛍️",
    lat: 26.2588,
    lng: 127.6975,
    address: "沖縄県浦添市西洲3-1-1",
    mapCode: "33 339 024*42",
    googleQuery: "サンエー浦添西海岸 PARCO CITY",
    tags: ["停留5小時", "250間店鋪", "Loft/3COINS", "無敵海景商城", "退稅服務中心"],
    desc: "沖繩規模最大、店鋪最全的海濱複合式巨型商城！整整5小時無死角血拼：無印良品超大門市、Loft生活雜貨、3COINS+plus、ABC-Mart Grand Stage、BEAMS、URBAN RESEARCH、ZARA等，走累了隨處都有落地玻璃窗可眺望西海岸海景！",
    tips: "2F設有外國遊客免稅服務專櫃，可統整全館發票辦理退稅；館內提供免費置物櫃可寄放大包小包。"
  },
  {
    id: "d4-6",
    day: 4,
    date: "2026/12/15",
    time: "17:39",
    name: "Workman Plus Urasoe Kyozuka",
    nameZh: "WORKMAN Plus 浦添經塚店",
    nameJa: "ワークマンプラス 浦添経塚店",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "shopping",
    categoryLabel: "機能工裝神店",
    icon: "🧥",
    lat: 26.2410,
    lng: 127.7208,
    address: "沖縄県浦添市字前田1064-1 (經塚站周邊)",
    mapCode: "33 253 456*11",
    googleQuery: "WORKMAN Plus 浦添経塚店",
    tags: ["日本爆紅神店", "防潑水風衣", "平價極致機能", "工裝休閒"],
    desc: "近年橫掃日本時尚圈的平價機能之王！以專業工裝品質打造戶外露營、防風防潑水外套、休閒彈性長褲與防滑鞋履，價格驚人親民（一件防風外套僅約1900-2900日圓），深受戶外旅行者推崇！",
    tips: "尺寸容易斷碼，看到喜歡的款式與尺寸建議立即下手；附有免費停車場。"
  },
  {
    id: "d4-7",
    day: 4,
    date: "2026/12/15",
    time: "18:52",
    name: "Katsunoya Naha Main Place",
    nameZh: "かつ乃屋 那霸Main Place店",
    nameJa: "かつ乃屋 那覇メインプレイス店",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "food",
    categoryLabel: "酥脆日式炸豬排",
    icon: "🍱",
    lat: 26.2238,
    lng: 127.6948,
    address: "沖縄県那覇市おもろまち4丁目4-9 (那霸Main Place 1F)",
    mapCode: "33 188 560*22",
    googleQuery: "かつ乃屋 那覇メインプレイス店",
    tags: ["新都心Main Place", "日式厚切豬排", "高麗菜絲免費續", "酥脆爽口"],
    desc: "新都心Main Place內的高人氣日式炸豬排專門店！精選熟成豬肉裹上生麵包粉酥炸至金黃酥脆，咬下去卡滋作響，肉質鮮嫩彈牙。白飯、味噌湯與爽口高麗菜絲皆可免費續添！",
    tips: "搭配特製豬排醬與現磨白芝麻更添香氣；位於Main Place內方便順道逛超市與服飾店。"
  },
  {
    id: "d4-8",
    day: 4,
    date: "2026/12/15",
    time: "20:03",
    name: "沖繩豬排小やじ 那霸店",
    nameZh: "豚かつ 小やじ 那霸店 (隱藏版極品阿古豬)",
    nameJa: "豚かつ 小やじ (Tonkatsu Koyaji)",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "food",
    categoryLabel: "私房職人豬排",
    icon: "🥢",
    lat: 26.2148,
    lng: 127.6912,
    address: "沖縄県那覇市牧志",
    mapCode: "33 158 544*77",
    googleQuery: "豚かつ 小やじ 那覇",
    tags: ["阿古豬專賣", "低溫慢炸熟成", "夢幻粉嫩肉質", "老饕私藏居酒屋"],
    desc: "老饕才懂得找尋的極品炸豬排居酒屋！嚴選沖繩頂級阿古豬，採用高超的低溫慢炸烹調法，肉質保留最誘人的粉嫩玫瑰色，油脂甘甜化口、肉汁滿溢，搭配特選海鹽與芥末，一嚐難忘！",
    tips: "店內座位精巧溫馨，適合點份特上炸豬排搭配沖繩在地生啤酒或泡盛共度美味夜晚。"
  },
  {
    id: "d4-9",
    day: 4,
    date: "2026/12/15",
    time: "21:32",
    name: "Ocean Tree",
    nameZh: "Ocean Tree (最後夜宿整理)",
    nameJa: "オーシャンツリー",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "hotel",
    categoryLabel: "旅宿晚安",
    icon: "🌙",
    lat: 26.1360,
    lng: 127.6780,
    address: "沖縄県糸満/南部海岸エリア",
    mapCode: "232 456 123*45",
    googleQuery: "Ocean Tree Okinawa",
    tags: ["打包行李", "行李秤重", "最後一晚"],
    desc: "在Ocean Tree的最後一晚！整理過去四天滿載的購物戰利品，進行行李箱秤重分裝，確認重要護照證件與明天的還車航班流程，在海浪聲中進入甜美夢鄉。",
    tips: "液體類（泡盛、保養品、化妝水）務必打包托運，隨身僅帶必要證件與貴重物品。"
  },

  // DAY 5 (2026/12/16)
  {
    id: "d5-1",
    day: 5,
    date: "2026/12/16",
    time: "08:00",
    name: "Ocean Tree",
    nameZh: "Ocean Tree (退房手續・告別海之樹)",
    nameJa: "オーシャンツリー",
    duration: "停留 02時00分",
    durationMinutes: 120,
    category: "hotel",
    categoryLabel: "退房告別",
    icon: "🧳",
    lat: 26.1360,
    lng: 127.6780,
    address: "沖縄県糸満/南部海岸エリア",
    mapCode: "232 456 123*45",
    googleQuery: "Ocean Tree Okinawa",
    tags: ["2小時打包退房", "海景道別", "全車上行李"],
    desc: "最後一天早晨！預留充足的2小時悠閒享受旅宿最後的海景晨光、拍照留念、徹底檢查房間有無遺漏充電線或衣物，辦理Check-out將行李全數上車，開啟最終日採購與美食之旅。",
    tips: "檢查後車廂空間分配；隨身攜帶日幣零錢與加油收據準備午後還車。"
  },
  {
    id: "d5-2",
    day: 5,
    date: "2026/12/16",
    time: "10:08",
    name: "道之驛 豐崎",
    nameZh: "道之驛 豐崎 (日本最西端道之驛)",
    nameJa: "道の駅 豊崎 (菜々色畑)",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "shopping",
    categoryLabel: "小農伴手禮",
    icon: "🥭",
    lat: 26.1585,
    lng: 127.6575,
    address: "沖縄県豊見城市字豊崎3-39",
    mapCode: "232 544 195*55",
    googleQuery: "道の駅 豊崎 Roadside Station Toyosaki",
    tags: ["日本最西端道の駅", "小農生鮮", "手作黑糖", "地產地消"],
    desc: "獲認證為日本最西端之道之驛！館內「菜菜色畑」販售沖繩南部農家清晨現採的新鮮蔬果、手工柴燒黑糖、芒果乾、紅芋脆片與特產調味料，是挑選道地小農伴手禮的絕佳私房寶地。",
    tips: "附設觀光情報中心，可拿取最新沖繩旅遊地圖與機場最新指引資訊。"
  },
  {
    id: "d5-3",
    day: 5,
    date: "2026/12/16",
    time: "11:20",
    name: "永忘 那霸店",
    nameZh: "永旺 那霸店 (AEON 那霸小祿店)",
    nameJa: "イオン那覇店 (AEON Naha Store)",
    duration: "停留 03時00分",
    durationMinutes: 180,
    category: "shopping",
    categoryLabel: "最後採買衝刺",
    icon: "🛒",
    lat: 26.1965,
    lng: 127.6668,
    address: "沖縄県那覇市金城5丁目10-2 (單軌小祿站直通)",
    mapCode: "33 095 154*14",
    googleQuery: "イオン那覇店 AEON Naha",
    tags: ["直通小祿站", "專屬免稅櫃台", "沖繩伴手禮總匯", "大型超市"],
    desc: "行程文字註記之「永忘 那霸店」即為與單軌小祿站直通的超大型「AEON 永旺 那霸店」！離機場僅約8分鐘車程，擁有專屬免稅櫃台，可一口氣掃購雪鹽餅乾、辣蝦餅、黑糖、泡盛、藥妝與各款限定商品，作返台前最後的大衝刺！",
    tips: "地下1F設有大型超市與伴手禮專區；館內室內停車場車位充足不怕日曬。"
  },
  {
    id: "d5-4",
    day: 5,
    date: "2026/12/16",
    time: "14:23",
    name: "琉球新麵 通堂 小祿本店",
    nameZh: "琉球新麵 通堂 小祿本店 (男人麵・女人麵)",
    nameJa: "琉球新麺 通堂 小禄本店",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "food",
    categoryLabel: "拉麵傳奇收尾",
    icon: "🍜",
    lat: 26.1973,
    lng: 127.6675,
    address: "沖縄県那覇市金城5-4-6 (AEON那霸店斜對面)",
    mapCode: "33 095 245*88",
    googleQuery: "琉球新麺 通堂 小禄本店",
    tags: ["沖繩第一拉麵", "男味濃豚骨", "女味清鹽雞湯", "無限免費辣豆芽"],
    desc: "沖繩最具代表性的傳奇拉麵名店！就在AEON那霸店斜對面。招牌「男味」濃郁黑蒜豚骨高湯搭配特選叉燒，「女味」則是以久米島天然海鹽熬煮的清雅金黃雞湯；桌上無限量享用的特製辣豆芽爽脆開胃，為沖繩美食之旅畫下完美句點！",
    tips: "門口採投幣式食券機點餐；若遇排隊通常翻桌率極快，15-20分鐘即可入座。"
  },
  {
    id: "d5-5",
    day: 5,
    date: "2026/12/16",
    time: "15:27",
    name: "Toyota租車沖繩那霸機場店（還車處）",
    nameZh: "Toyota租車 那霸機場店 (還車處)",
    nameJa: "トヨタレンタカー 那覇空港店 (返却)",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "transport",
    categoryLabel: "還車手續",
    icon: "⛽",
    lat: 26.1915,
    lng: 127.6590,
    address: "沖縄県那覇市赤嶺2丁目13-1",
    mapCode: "33 064 577*55",
    googleQuery: "Toyota Rental Car Naha Airport Branch Return",
    tags: ["加滿油歸還", "出示加油單據", "免費機場接駁車"],
    desc: "自駕行程順利返抵豐田租車那霸機場店。鄰近加油站依約加滿汽油（出示加油發票或收據供工作人員查驗），檢查車廂座位有無遺落行李，完成驗車後搭乘免費專車接駁至那霸機場國際線航廈。",
    tips: "店舖旁即有ENEOS加油站，加滿油（油種：レギュラー Regular）並保留完整收據。"
  },
  {
    id: "d5-6",
    day: 5,
    date: "2026/12/16",
    time: "16:50",
    name: "那霸機場",
    nameZh: "那霸機場 國際線航廈 (返程返台)",
    nameJa: "那覇空港 国際線ターミナル (OKA)",
    duration: "停留 01時00分",
    durationMinutes: 60,
    category: "transport",
    categoryLabel: "登機返台",
    icon: "✈️",
    lat: 26.2065,
    lng: 127.6465,
    address: "沖縄県那覇市鏡水150",
    mapCode: "33 123 279*00",
    googleQuery: "Naha Airport International Terminal OKA",
    tags: ["國際線託運", "DFS免稅提貨", "機場最後買伴手禮", "旅途平安返台"],
    desc: "抵達那霸機場辦理航空公司登機報到與行李託運手續。通關後至DFS免稅提貨櫃台領取第3天採購的免稅商品，候機期間可在機場免稅店補買Royce生巧克力、沖繩紅芋塔，帶著滿滿戰利品與蔚藍回憶登機返台！",
    tips: "國際線建議於起飛前2小時至2.5小時完成報到；托運行李注意重量限制。"
  }
];

const PACKING_CHECKLIST_DATA = [
  { id: "p1", category: "documents", categoryName: "重要證件與金融", text: "台灣駕照正本 (自駕不可或缺，千萬不可忘記！)", essential: true },
  { id: "p2", category: "documents", categoryName: "重要證件與金融", text: "日文譯本 (監理所申辦有效期限內，非國際駕照！)", essential: true },
  { id: "p3", category: "documents", categoryName: "重要證件與金融", text: "護照 (有效期需6個月以上)", essential: true },
  { id: "p4", category: "documents", categoryName: "重要證件與金融", text: "日本Visit Japan Web入境QR Code截圖備存", essential: true },
  { id: "p5", category: "documents", categoryName: "重要證件與金融", text: "信用卡 (回饋高/免海外手續費卡片至少2張)", essential: true },
  { id: "p6", category: "documents", categoryName: "重要證件與金融", text: "日圓現金 (部分小吃、神社御守與停車場需現金)", essential: true },
  { id: "p7", category: "documents", categoryName: "重要證件與金融", text: "台灣好市多Costco實體會員卡 (第1天採購必備)", essential: true },
  
  { id: "p8", category: "electronics", categoryName: "3C電器與自駕", text: "日本eSIM卡或實體漫遊網卡 (網路通暢最重要)", essential: true },
  { id: "p9", category: "electronics", categoryName: "3C電器與自駕", text: "行動電源 (需隨身攜帶上飛機，禁止托運)", essential: true },
  { id: "p10", category: "electronics", categoryName: "3C電器與自駕", text: "車用手機支架 (自駕導航看Google Maps極度實用)", essential: false },
  { id: "p11", category: "electronics", categoryName: "3C電器與自駕", text: "Type-C / Lightning充電線與車用點菸器轉接頭", essential: false },
  { id: "p12", category: "electronics", categoryName: "3C電器與自駕", text: "便攜式行李電子秤 (最後兩天血拼秤重必備)", essential: false },

  { id: "p13", category: "clothing", categoryName: "衣物穿搭", text: "防風連帽薄外套 (12月沖繩海風強勁、早晚偏涼)", essential: true },
  { id: "p14", category: "clothing", categoryName: "衣物穿搭", text: "洋蔥式好穿脫長袖/短袖上衣、舒適長褲", essential: true },
  { id: "p15", category: "clothing", categoryName: "衣物穿搭", text: "好走運動布鞋 (PARCO CITY逛5小時與市場走路必備)", essential: true },
  { id: "p16", category: "clothing", categoryName: "衣物穿搭", text: "抗UV太陽眼鏡 (白天海島駕車與陽光海景必備)", essential: false },

  { id: "p17", category: "convenience", categoryName: "便利好物與生活", text: "折疊大容量購物袋/行李軟袋 (好市多與商場戰利品)", essential: true },
  { id: "p18", category: "convenience", categoryName: "便利好物與生活", text: "隨身純水濕紙巾 (海鮮魚市場與路邊小吃必備)", essential: false },
  { id: "p19", category: "convenience", categoryName: "便利好物與生活", text: "個人常備藥品 (胃腸藥、止痛藥、暈車藥、OK繃)", essential: false },
  { id: "p20", category: "convenience", categoryName: "便利好物與生活", text: "晴雨兩用摺疊傘 (應對偶發海島陣雨)", essential: false }
];

const TRAVEL_TIPS = {
  weather: {
    tempRange: "16°C ~ 22°C",
    season: "初冬海島乾爽涼爽氣候",
    clothing: "早晚海風大，白天天氣晴朗舒適。推薦「洋蔥式穿法」：短袖或薄長袖內搭，外加一件輕便防風外套，兼顧室內商場暖氣與海邊海風。",
    highlights: [
      "12月是沖繩乾季，降雨天數遠少於夏季颱風季，是自駕旅遊的好時節。",
      "海風吹拂時體感溫度會稍低3-4度，尤其在美國村海濱、美麗SUN海灘及瀨長島務必穿防風外套。",
      "冬季海水偏涼不建議下水游泳，但沙灘漫步與看飛機視野極佳。"
    ]
  },
  driving: {
    side: "日本左側通行 (右駕)",
    essentials: "台灣旅客需同時備齊「台灣有效駕照正本」與「日文譯本正本」（監理所申辦，非國際駕照！）。",
    rules: [
      { title: "轉彎口訣", desc: "牢記「左小轉、右大轉」；右轉時必須在路口中心等候，禮讓對向直行車輛全部通過後方能轉彎。" },
      { title: "方向燈與雨刷", desc: "日系車方向燈撥桿在右手邊，雨刷在左手邊。初期容易誤刷雨刷，放慢動作即可。" },
      { title: "行人絕對優先", desc: "無號誌或綠燈路口，若有行人踏上斑馬線，必須完全靜止停下等待行人通過。" },
      { title: "導航 MapCode", desc: "本網站每站皆已標記專屬 MapCode，上車輸入車機即可精準導航，亦可搭配 Google Maps。" },
      { title: "還車滿油規定", desc: "最後一天還車前，必須在營業所附近指定加油站加滿油（滿タン，Regular汽油），保留發票核對。" }
    ]
  },
  foodBucketList: [
    { name: "沖繩麵 (ソーキそば)", desc: "傳統甘甜柴魚高湯與入口即化豬軟骨，田舍與EIBUN雙派系必吃", icon: "🍲" },
    { name: "現剖生魚片與焗烤龍蝦", desc: "糸滿魚市場一盒300-500円銅板價，爽吃甜蝦、海膽與現開生蠔", icon: "🍣" },
    { name: "敘敘苑海景午間燒肉", desc: "PARCO CITY落地窗賞西海岸蔚藍海景，頂級牛舌與極品牛五花", icon: "🥩" },
    { name: "奶油香煎時令鮮魚", desc: "糸滿漁民食堂招牌鐵板奶油蒜香煎魚，外皮焦香酥脆、魚肉多汁鮮美", icon: "🐟" },
    { name: "琉球新麵 通堂", desc: "經典男味黑蒜豚骨與女味久米島天然鹽味雞湯，滿桌免費辣豆芽", icon: "🍜" },
    { name: "沖繩阿古豬炸豬排", desc: "かつ乃屋金黃酥脆與小やじ極品低溫慢炸熟成粉嫩阿古豬排", icon: "🍱" },
    { name: "南城好市多限定熟食", desc: "沖繩首店限定風味美式熱狗披薩與牛肉捲", icon: "🍕" }
  ]
};
